DROP TABLE IMAGE_OBJECT;
DROP TABLE IMAGE_DATASET;
DROP TABLE IMAGE;
DROP TABLE VIDEO;
DROP TABLE DATASET;
DROP TABLE OBJECT;
CREATE TABLE VIDEO(
VideoID	INT	AUTO_INCREMENT,
Name	varchar(250),
Duration	INT,
PostalZipCode	varchar(50),
PRIMARY KEY(VideoID)
);

CREATE TABLE IMAGE(
ImageID	INT	AUTO_INCREMENT,
Name varchar(500) NOT NULL,
VideoID	INT	NOT NULL,
PRIMARY KEY(ImageID),
FOREIGN KEY(VideoID) REFERENCES VIDEO(VideoID)
);

CREATE TABLE DATASET(
DatasetID	INT	AUTO_INCREMENT	NOT NULL,
Name	varchar(250),
LicenceFee	decimal,
DatetimeCreated	datetime	NOT NUlL,
PRIMARY KEY(DatasetID)
);

CREATE TABLE OBJECT(
ObjectID	INT	AUTO_INCREMENT	NOT NULL,
Name	varchar(100),
Value	decimal(4,2),
PRIMARY KEY(ObjectID)
);

CREATE TABLE IMAGE_OBJECT(
ImageObjectID	INT	AUTO_INCREMENT	NOT NULL,
ImageID	INT	NOT NULL,
ObjectID	INT	NOT NULL,
BoundingBoxX	INT	NOT NULL,
BoundingBoxY	INT	NOT NULL,
BoundingBoxW	INT	NOT NULL,
BoundingBoxH	INT	NOT NULL,
PRIMARY KEY(ImageObjectID),
FOREIGN KEY(ImageID) REFERENCES IMAGE(ImageID),
FOREIGN KEY(ObjectID) REFERENCES OBJECT(ObjectID)
);

CREATE TABLE IMAGE_DATASET(
ImageDatasetID	INT	AUTO_INCREMENT	NOT NULL,
ImageID	INT	NOT NULL,
DatasetID	INT	NOT NULL,
PRIMARY KEY(ImageDatasetID),
FOREIGN KEY(ImageID) REFERENCES IMAGE(ImageID),
FOREIGN KEY(DatasetID) REFERENCES DATASET(DatasetID)
);
